/**
 * .env File Parser & Generator
 *
 * Handles parsing .env file content into key-value pairs and
 * generating .env formatted strings for download.
 */

export interface EnvEntry {
    key: string;
    value: string;
}

/**
 * Parse a .env file content string into an array of key-value pairs.
 * Handles comments, empty lines, quoted values, and inline comments.
 *
 * @param content - Raw .env file content
 * @returns Array of { key, value } pairs
 */
export function parseEnvFile(content: string): EnvEntry[] {
    const entries: EnvEntry[] = [];
    const lines = content.split(/\r?\n/);

    for (const line of lines) {
        const trimmed = line.trim();

        // Skip empty lines and comments
        if (!trimmed || trimmed.startsWith('#')) {
            continue;
        }

        // Match KEY=VALUE pattern
        const eqIndex = trimmed.indexOf('=');
        if (eqIndex === -1) continue;

        const key = trimmed.substring(0, eqIndex).trim();
        let value = trimmed.substring(eqIndex + 1).trim();

        // Skip invalid keys
        if (!key || /\s/.test(key)) continue;

        // Handle quoted values
        if (
            (value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'"))
        ) {
            value = value.slice(1, -1);
        }

        entries.push({ key, value });
    }

    return entries;
}

/**
 * Generate a .env formatted string from an array of key-value pairs.
 *
 * @param entries - Array of { key, value } pairs
 * @returns Formatted .env file content string
 */
export function generateEnvFile(entries: EnvEntry[]): string {
    const header = `# Generated by dotENV\n# ${new Date().toISOString()}\n\n`;

    const lines = entries.map(({ key, value }) => {
        // Wrap in quotes if value contains spaces, #, or special chars
        if (value.includes(' ') || value.includes('#') || value.includes('=')) {
            return `${key}="${value}"`;
        }
        return `${key}=${value}`;
    });

    return header + lines.join('\n') + '\n';
}
